// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-3MbTBwk7beUiry44oT-1oJAi9ZLZVmU',
    appId: '1:254603231116:web:4a3f8731159b980c9aa0a9',
    messagingSenderId: '254603231116',
    projectId: 'careful-engine-447006-v6',
    authDomain: 'careful-engine-447006-v6.firebaseapp.com',
    storageBucket: 'careful-engine-447006-v6.firebasestorage.app',
    measurementId: 'G-XC493XBFC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl6yE3C25XCjn2cPUNSqoRsc0vFzy-I1o',
    appId: '1:254603231116:android:fd8444e76cc1ac789aa0a9',
    messagingSenderId: '254603231116',
    projectId: 'careful-engine-447006-v6',
    storageBucket: 'careful-engine-447006-v6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuHmBqdNyMNklKZb6pfqQmGxyhPcFBFd0',
    appId: '1:254603231116:ios:849065f31edff1ba9aa0a9',
    messagingSenderId: '254603231116',
    projectId: 'careful-engine-447006-v6',
    storageBucket: 'careful-engine-447006-v6.firebasestorage.app',
    iosBundleId: 'com.example.quanLyChiTieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuHmBqdNyMNklKZb6pfqQmGxyhPcFBFd0',
    appId: '1:254603231116:ios:849065f31edff1ba9aa0a9',
    messagingSenderId: '254603231116',
    projectId: 'careful-engine-447006-v6',
    storageBucket: 'careful-engine-447006-v6.firebasestorage.app',
    iosBundleId: 'com.example.quanLyChiTieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-3MbTBwk7beUiry44oT-1oJAi9ZLZVmU',
    appId: '1:254603231116:web:c739c90577c3aa659aa0a9',
    messagingSenderId: '254603231116',
    projectId: 'careful-engine-447006-v6',
    authDomain: 'careful-engine-447006-v6.firebaseapp.com',
    storageBucket: 'careful-engine-447006-v6.firebasestorage.app',
    measurementId: 'G-4Y1FWGWWDN',
  );
}
