// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOvVr5aH1YYXHoWxnpMx4DjenJcIPVNts',
    appId: '1:90050268720:web:61edafc5b9e6d1f45427f5',
    messagingSenderId: '90050268720',
    projectId: 'qlct-cblack',
    authDomain: 'qlct-cblack.firebaseapp.com',
    storageBucket: 'qlct-cblack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKXWxi1hhb9vUfCm-YTNRcyfP9h1DvUbA',
    appId: '1:90050268720:android:ae173388da9e41c55427f5',
    messagingSenderId: '90050268720',
    projectId: 'qlct-cblack',
    storageBucket: 'qlct-cblack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsAEDu_C8Pqf79ebvXlwBPmUdKqrQshug',
    appId: '1:90050268720:ios:06e2bf72e1dcb1e05427f5',
    messagingSenderId: '90050268720',
    projectId: 'qlct-cblack',
    storageBucket: 'qlct-cblack.firebasestorage.app',
    iosBundleId: 'com.example.quanLyChiTieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsAEDu_C8Pqf79ebvXlwBPmUdKqrQshug',
    appId: '1:90050268720:ios:06e2bf72e1dcb1e05427f5',
    messagingSenderId: '90050268720',
    projectId: 'qlct-cblack',
    storageBucket: 'qlct-cblack.firebasestorage.app',
    iosBundleId: 'com.example.quanLyChiTieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOvVr5aH1YYXHoWxnpMx4DjenJcIPVNts',
    appId: '1:90050268720:web:984f6364ca4076215427f5',
    messagingSenderId: '90050268720',
    projectId: 'qlct-cblack',
    authDomain: 'qlct-cblack.firebaseapp.com',
    storageBucket: 'qlct-cblack.firebasestorage.app',
  );

}